import type { AnalyticsSummary } from "@/types/analytics";

export const EMPTY_ANALYTICS_SUMMARY: AnalyticsSummary = {
  currency: "USD",
  tradeCount: 0,
  closedTradeCount: 0,
  openTradeCount: 0,
  netPnl: "0.00",
  grossProfit: "0.00",
  grossLoss: "0.00",
  returnPercentage: null,
  winCount: 0,
  lossCount: 0,
  breakevenCount: 0,
  winRate: null,
  lossRate: null,
  breakevenRate: null,
  profitFactor: null,
  moneyExpectancy: null,
  rExpectancy: null,
  totalR: null,
  averageR: null,
  averageWinner: null,
  averageLoser: null,
  averageWinLossRatio: null,
  largestWinner: null,
  largestLoser: null,
  averageHoldingTimeMinutes: null,
  medianHoldingTimeMinutes: null,
  totalCommission: "0.00",
  totalSwap: "0.00",
  totalFees: "0.00",
  totalTradingCosts: "0.00",
  maxDrawdownAmount: "0.00",
  maxDrawdownPercentage: "0.00",
  currentDrawdownAmount: "0.00",
  currentDrawdownPercentage: "0.00",
  longestWinningStreak: 0,
  longestLosingStreak: 0,
  currentWinningStreak: 0,
  currentLosingStreak: 0,
  startingBalance: "0.00",
  currentBalance: "0.00",
  currentOpenRisk: "0.00",
  sampleConfidence: "INSUFFICIENT",
  equityCurve: [],
  calendar: [],
};
